# Generated by Django 5.2.7 on 2025-11-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(db_index=True, max_length=64)),
                ('section_index', models.PositiveIntegerField()),
                ('condition_id', models.CharField(max_length=64)),
                ('started_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('ended_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['participant_id', 'section_index'], name='appsetup_tr_partici_7f71e3_idx')],
            },
        ),
    ]
