# Generated by Django 5.2.7 on 2025-11-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triallog',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triallog',
            name='wpm',
            field=models.FloatField(blank=True, help_text='Words per minute for this trial (derived from word_count and duration_ms)', null=True),
        ),
    ]
