# Generated by Django 5.2.7 on 2025-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetup', '0002_triallog_word_count_triallog_wpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ranked_conditions', models.JSONField(help_text='Ordered list of condition IDs from most to least preferred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
