# Generated by Django 5.2.7 on 2025-12-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetup', '0003_preferencesurvey'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='triallog',
            name='appsetup_tr_partici_7f71e3_idx',
        ),
        migrations.RemoveField(
            model_name='triallog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='triallog',
            name='ended_at_ms',
        ),
        migrations.RemoveField(
            model_name='triallog',
            name='section_index',
        ),
        migrations.RemoveField(
            model_name='triallog',
            name='started_at_ms',
        ),
        migrations.AlterField(
            model_name='preferencesurvey',
            name='ranked_conditions',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='triallog',
            index=models.Index(fields=['participant_id'], name='appsetup_tr_partici_0cc758_idx'),
        ),
    ]
