# Generated by Django 6.0.3 on 2026-04-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetup', '0004_remove_triallog_appsetup_tr_partici_7f71e3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='triallog',
            name='appsetup_tr_partici_0cc758_idx',
        ),
        migrations.AlterField(
            model_name='triallog',
            name='wpm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
